name: dap_final_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - altair
  - streamlit
  - folium
  - branca
  - geopy
  - requests
  - python-dateutil
  - pip
  - pip:
      - earthengine-api
      - streamlit-folium